name: Keeper Secrets

on: [push]

jobs:
  keep-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Keeper CLI
      run: |
        curl https://keepersecurity.com/download/kcli/linux/latest -o /tmp/kcli
        sudo install /tmp/kcli /usr/local/bin/kcli
    - name: Log in to Keeper
      env:
        KEEPER_EMAIL: ${{ secrets.praveenpm001@gmail.com }}
        KEEPER_PASSWORD: ${{ secrets.Password@123 }}
      run: |
        kcli login -e $KEEPER_EMAIL -p $KEEPER_PASSWORD
    - name: Get secret
      env:
        SECRET_NAME: ${{ secrets.praveen-github }}
      run: |
        kcli get record "$SECRET_NAME" -f json > secret.json